Refactor/book db conn
library-angels/code-library-backend pull request #170
Opened 2020-11-30 13:52 UTC by Urhengulas

* `helpers::db`: Let `run_migration` take `PgConnection`
    --> My optimal solution would be to take a generic connection, but couldn't figure out how to do it:
    ```rust
    fn run_migration(
        run_embedded_migration: impl FnOnce(&impl Connection<Backend = Pg>) -> Result<(), RunMigrationsError>,
        db_conn: &impl Connection<Backend = Pg>,
    ) 
    ```
* `book`: Mv `db_conn` into server

2020-11-30 16:10 UTC, code-mm requested changes

2020-11-30 16:15 UTC, code-mm commented
1. Please remove the changes in other services than the book service. That is quite confusing.
2. I do not see the benefit in establishing a `PgConnection` in main to run the migration and then creating another pool in the server. In my understanding this just takes more time to start the service. Cloning an `Arc<T>` is less expensive than establishing multiple database connections. Can you please elaborate it bit on this change?

2020-11-30 16:33 UTC, Urhengulas commented on book/src/lib/lib.rs
> +// pub use crate::db::{DbConn, DbPool};
Ups, actually I want to export it for the tests, but I will do that in the test PR 😬

2020-11-30 16:40 UTC, Urhengulas commented
>     1. Please remove the changes in other services than the book service. That is quite confusing.
> 
>     2. I do not see the benefit in establishing a `PgConnection` in main to run the migration and then creating another pool in the server. In my understanding this just takes more time to start the service. Cloning an `Arc<T>` is less expensive than establishing multiple database connections. Can you please elaborate it bit on this change?

The reason for handing over a PgConnection is, that I'd like to move the establishing of the `Pool` into my `BookServer::new(..., database_url)`. In my bestcase I'd give the `helper::db::run_migration` the above signature, so it can take both `PgConnection` and `PooledConnection`, but this somehow doesn't work. I will revert that and create the `Pool` outside of `BookServer::new` for now..

2020-12-02 09:59 UTC, code-mm approved these changes

2020-12-02 11:35 UTC, merged